// Generated by CoffeeScript 1.6.2
var conf;

conf = require('nconf');

conf.defaults({
  api: {
    host: "api.searchtower.com"
  },
  routes: {
    getUserAceess: {
      uri: "/v1/indexes/{{index}}/acl",
      method: "GET"
    },
    updateUserAccess: {
      uri: "/v1/indexes/{{index}}/acl",
      method: "PUT"
    },
    deleteUserAccess: {
      uri: "/v1/indexes/{{index}}/acl",
      method: "DELETE"
    },
    createIndex: {
      uri: "/v1/indexes",
      method: "POST"
    },
    updateIndex: {
      uri: "/v1/indexes/{{index}}",
      method: "PUT"
    },
    listIndex: {
      uri: "/v1/indexes",
      method: "GET"
    },
    getIndex: {
      uri: "/v1/indexes/{{index}}",
      method: "GET"
    },
    deleteIndex: {
      uri: "/v1/indexes/{{index}}",
      method: "DELETE"
    },
    addDocument: {
      uri: "/v1/documents/{{index}}/{{name}}",
      method: "PUT"
    },
    listDocuments: {
      uri: "/v1/documents/{{index}}",
      method: "GET"
    },
    downloadDocument: {
      uri: "/v1/documents/{{index}}/{{name}}",
      method: "GET"
    },
    deleteDocument: {
      uri: "/v1/documents/{{index}}/{{name}}",
      method: "DELETE"
    },
    restoreDocument: {
      uri: "/v1/documents/{{index}}/{{name}}/restore",
      method: 'POST'
    },
    documentDetails: {
      uri: "/v1/search/{{index}}/{{name}}",
      method: "GET"
    },
    search: {
      uri: "/v1/search/{{index}}",
      method: "POST"
    }
  }
});

module.exports = conf;
